# Generated by Django 3.2.16 on 2022-10-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantowner',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
