# Generated by Django 3.2.16 on 2022-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_restaurantowner_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurantowner',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='restaurantowner',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='restaurantowner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='restaurantowner',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='restaurantowner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='restaurantowner',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='restaurantowner',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='restaurantowner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='restaurantowner',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='restaurantowner',
            name='username',
        ),
        migrations.AlterField(
            model_name='restaurantowner',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantowner',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantowner',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
