# Generated by Django 3.2.12 on 2022-10-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_auto_20221029_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantowner',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
