# Generated by Django 3.2.12 on 2022-10-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_restaurantowner_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantowner',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='media/QrCodeImages'),
        ),
    ]
