# Generated by Django 3.2.12 on 2022-10-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_restaurantowner_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantowner',
            name='qr_code',
        ),
    ]
